name: dash_coverage #Environment name
dependencies:
  - python=3.10
  - pip:
    - dash==2.3.1
    - multiprocess
    - dash_bootstrap_components
    - gunicorn==20.0.4
    - pandas==1.1.4
    - plotly==5.6.0
    - rtree
    - skyfield==1.40
    - geopandas==0.10.2
    - folium 
    - branca
    - matplotlib 
    - mapclassify